# Homework-2

## Part 1, Working with Numpy
    Your goal is to calculate the final grade for studnets in a class. 
      1. We have 10 Students in class, and 5 assessment score ( Homework, Project, Exam1, Exam2, Final Exam)for each
      student. Create a matrix containing grades of students, (rows are students, columns are assessments). Use for loop and input  function for entering the student name and grades. Enter arbitary grades from 0 to 100 for each assessment 
        2. Create a weigth vector containing weight of each assessment. Example (15%, 15%, 20%, 20%, 30% )
        3. Calculate the final grade for each students. Use Numpy to create your vector, matrix and calculating final grade.
        4. Convert final grades to letter format(90%-100% = A, 80%-89% = B, 70%-79% =C, 60%-69%=D and F for less than 60% )
        5. print out Student names and their grades

## Part 2, Working with Pandas

    - Step 1: Download the titanic.csv file from github.


    - Step 2: Read the file in Python and store it in a dataframe.


    - Step 3: Explore the data in your Jupyter notebook, eg. general info about data, some basic stats.
      Also print out the data for row index 100-105 and columns 'Name', 'Age', 'Fare'


    - Step 4: Create two dataframes, one containing data for only Categorical Variables and one for only Quantitative variable
  
    - Step 5: Write these newly created dataframe in .csv files.

## Part 1 Answers

In [ ]:
import numpy as np
names = []
names = input("Please enter the five students names with spaces").split()

In [ ]:
for names in names:
assessment_grades = input("Please enter 5 grades for {name} seperated by space based on HW, Project, Exam1, Exam2 and FinalExam:").split()
assessment_grades = [float(g) for g in grades]
final_grade = sum(assessment_grades)
if final_grade >= 89: letter_grade = 'A'
if final_grade >= 79: letter_grade = 'B'
if final_grade >= 69: letter_grade = 'C'
if final_grade >= 59: letter_grade = 'D'
if final_grade <= 59: letter_grade = 'F'
print(names)
print(final_grade)

## Part 2 Answers

In [32]:
import pandas as pd
df = pd.read_csv('titanic.csv')

In [11]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [13]:
df.loc[100:105,['Name', 'Age', 'Fare']]

                                 Name   Age     Fare
100            Petranec, Miss Matilda  28.0   7.8958
101  Petroff, Mr. Pastcho ("Pentcho")   NaN   7.8958
102         White, Mr. Richard Frasar  21.0  77.2875
103        Johansson, Mr. Gustaf Joel  33.0   8.6542
104    Gustafsson, Mr. Anders Vilhelm  37.0   7.9250
105             Mionoff, Mr. Stoytcho  28.0   7.8958

In [19]:
categorical = df[['PassengerId', 'Name', 'Sex', 'Ticket', 'Cabin', 'Embarked']]
categorical.head()

,PassengerId,Name,Sex,Ticket,Cabin,Embarked
0,1,"Braund, Mr. Owen Harris",male,A/5 21171,NaN,S
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,PC 17599,C85,C
2,3,"Heikkinen, Miss Laina",female,STON/O2. 3101282,NaN,S
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,113803,C123,S
4,5,"Allen, Mr. William Henry",male,373450,NaN,S

In [21]:
quantitative = df[['Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare']]
quantitative.head()

   Survived  Pclass   Age  SibSp  Parch     Fare
0         0       3  22.0      1      0   7.2500
1         1       1  38.0      1      0  71.2833
2         1       3  26.0      0      0   7.9250
3         1       1  35.0      1      0  53.1000
4         0       3  35.0      0      0   8.0500